#!/usr/bin/with-contenv bash

chmod +x /utils/port.sh
chown abc:abc /utils/port.sh
crontab -u abc -r

while true; do
    FILE=/gluetun/tmp/forwarded_port
	if [[ -f "$FILE" ]]; then
		PORT=$(cat $FILE)
		if [[ ! -z $PORT && $PORT -ne 0 ]]; then
			break
		fi
	fi
	sleep 10
done

echo "Received port: $PORT"

chmod 777 /config/settings.json
sed -i "/peer-port\"/c\    \"peer-port\": $PORT," /config/settings.json

echo "Enabling port crontab"
crontab -l | { cat; echo "*/10 0 0 0 0 /utils/port.sh 2>&1"; } | crontab -
